apiVersion: v1
kind: Service
metadata:
  name: my-app-backend
  namespace: default
  labels:
    app: my-app
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: my-app
    component: backend