apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: default
  labels:
    managed-by: iac-generator
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: postgres:15
        command: ["/bin/sh", "-c"]
        args: ["psql,-c,CREATE DATABASE IF NOT EXISTS myapp;"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"