apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-frontend
  namespace: default
  labels:
    app: my-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      component: frontend
  template:
    metadata:
      labels:
        app: my-app
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/my-project/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: BACKEND_URL
          value: "http://my-app-backend:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5